name = "backend"
compatibility_date = "2024-08-16"

[vars]
DATABASE_URL="	prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMzc5N2NkZTYtOGM5NS00ZGFiLWI1ZjEtMWNlZjQyZGRmMGI0IiwidGVuYW50X2lkIjoiYTVkZWJjNDEyNmQzNTE0ODA1ZjlkNTY5YWQ4YTRkZTM3NmViYTQzMTY2NmQzZDQxYzYyNjM0ZDRiNzIxZWQ4OCIsImludGVybmFsX3NlY3JldCI6ImUyY2FjMjRjLWYwMzctNGI2Yi1hZWE3LTIxMDc0YTBkZjZmNSJ9.bcyj-M2BQxqT6M1iKCa9A5XQkmg0Msz_kmEhFZsScdQ"
JWT_SECRET = "secret"
